kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-data
  namespace: devops
spec:
  storageClassName: alicloud-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
