apiVersion: apps/v1 
kind: Deployment
metadata:
  name: drone-agent-ssh
  namespace: devops
  labels:
    app: drone-agent-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-agent-ssh
  template:
    metadata:
      labels:
        app: drone-agent-ssh
    spec:
      containers:
      - image: drone/drone-runner-ssh:linux-amd64 
        name: drone-agent-ssh
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 200Mi
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 3000
#          initialDelaySeconds: 3
#          periodSeconds: 3
        env:
        - name: DRONE_RPC_DUMP_HTTP
          value: "true"
        - name: DRONE_RPC_DUMP_HTTP_BODY
          value: "true"
        - name: DRONE_UI_USERNAME
          value: "root"
        - name: DRONE_UI_PASSWORD
          value: "ZmRmODZkMTgwYjdj"
        - name: DRONE_RPC_HOST
          value: "drone.alphalawyer.cn"
        - name: DRONE_RPC_PROTO
          value: "https"
        # issue: https://github.com/drone/drone/issues/2048
        - name: DOCKER_API_VERSION
          value: "1.39"
        - name: DRONE_RPC_SECRET
          value: "eW91cnBhc3N3b3Jk"
        - name: DRONE_RUNNER_CAPACITY
          value: "10"
        - name: DRONE_RUNNER_NAME
          value: "first-ssh-runner"
        - name: DRONE_TRACE
          value: "true"
        - name: DRONE_DEBUG
          value: "true"
