apiVersion: v1
kind: Service
metadata:
  name: drone-svc
  namespace: devops
  labels:
    app: drone-svc
spec:
  ports:
    - name: drone-server-http
      port: 80
    - name: drone-server-https
      port: 443
  selector:
    app: droneserver
  type: ClusterIP
