apiVersion: v1
kind: Service
metadata:
  name: drone-agent-svc
  namespace: devops
  labels:
    app: drone-agent-svc
spec:
  ports:
    - name: drone-agent
      port: 3000
      targetPort: 3000
  selector:
    app: drone-agent
  type: ClusterIP
