kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-server
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
  storageClassName: alicloud-nas
