kind: Pod
apiVersion: v1
metadata:
  name: test-pod-1-12
spec:
  containers:
  - name: test-pod-1-12
    image: nginx:alpine
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
