apiVersion: v1
kind: Pod 
metadata:
  name: busybox-test
  labels:
    app: busybox-test
spec:
  nodeSelector:
    kubernetes.io/hostname: node5 
  containers:
  - name: busybox-test
    image: centos
    command:
    - sleep
    args:
    - "3600"
