kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-data
  namespace: kube-system
spec:
  storageClassName: alicloud-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
