apiVersion: v1
kind: Service
metadata:
  name: mongos-router-service-nodeport
  labels:
    name: mongos-router
  namespace: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32017
  type: NodePort
  selector:
    role: mongos-router  
  
  
