apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-block-elasticsearch-dev
  namespace: elasticsearch 
provisioner: ceph.rook.io/block
parameters:
  blockPool: elasticsearchpool
  clusterNamespace: rook-ceph
  fstype: xfs
reclaimPolicy: Retain
allowVolumeExpansion: true
