# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-dev
  namespace: elasticsearch
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elasticsearch
  name: elasticsearch-dev
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2
subjects:
- kind: ServiceAccount
  name: elasticsearch-dev
  namespace: elasticsearch
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"
