apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch
  labels:
    k8s-app: elasticsearch
    version: v6.3.2
spec:
  serviceName: elasticsearch
  replicas: 9
  selector:
    matchLabels:
      k8s-app: elasticsearch
      version: v6.3.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        version: v6.3.2
    spec:
      containers:
      - name: elasticsearch
        image: lincappu/elasticsearch-6.3.2-crack:prod-v2 
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: "4000m"
              memory: "30Gi"
            requests:
              cpu: "4000m"
              memory: "30Gi"
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: snapshot-data
          mountPath: /snapshot
        env:
          - name: cluster.name
            value: elasticsearch-dev
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch,elasticsearch-3.elasticsearch,elasticsearch-4.elasticsearch,elasticsearch-5.elasticsearch,elasticsearch-6.elasticsearch,elasticsearch-7.elasticsearch,elasticsearch-8.elasticsearch"
          - name: discovery.zen.minimum_master_nodes
            value: "5"
          - name: ES_JAVA_OPTS
            value: "-Xms26g -Xmx26g"
          - name: thread_pool.bulk.queue_size
            value: "1000"
      volumes:
      - name: snapshot-data
        hostPath:
          path: /snapshot
          type: Directory
      initContainers:
      - name: fix-permissions
        image: busybox
        imagePullPolicy: Never
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      - name: increase-ml-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -l unlimited"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata: 
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-storage-elasticsearch
      resources:
        requests:
          storage: 1000Gi
