apiVersion: v1
kind: Service
metadata:
  name: kibana-dev
  namespace: elasticsearch 
  labels:
    k8s-app: kibana-dev
    version: v6.3.2
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 32601
  type: NodePort
  selector:
    k8s-app: kibana-dev
    version: v6.3.2

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana-dev
  namespace: elasticsearch
  labels:
    k8s-app: kibana-dev
    version: v6.3.2
spec:
  serviceName: kibana-dev
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-dev
      version: v6.3.2
  template:
    metadata:
      labels:
        k8s-app: kibana-dev
        version: v6.3.2
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
      - name: kibana-dev
        image: docker.elastic.co/kibana/kibana:6.3.2
        resources:
          limits:
            cpu: 8000m
            memory: 16Gi
          requests:
            cpu: 8000m
            memory: 16Gi
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
            value: "true"
          - name: SERVER_NAME
            value: kibana-dev
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_PORT
            value: "5601"
#          - name: ELASTICSEARCH_USERNAME
#            value: "elastic"
#          - name: ELASTICSEARCH_PASSWORD
#            value: "admin123"
#          - name: SERVER_BASEPATH
#            value: "/kibana-dev"
        ports:
        - name: ui
          containerPort: 5601
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: ui
            httpHeaders:
            - name: Authorization
              value: "Basic ZWxhc3RpYzphZG1pbjEyMw=="
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: ui
            httpHeaders:
            - name: Authorization
              value: "Basic ZWxhc3RpYzphZG1pbjEyMw=="
          initialDelaySeconds: 5
          timeoutSeconds: 10
