apiVersion: v1
kind: Service
metadata:
  name: cerebro-dev
  namespace: elasticsearch
  labels:
    k8s-app: cerebro-dev
    version: v0.8.1
    kubernetes.io/name: "Cerebro"
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: ui
    nodePort: 32602
  selector:
    k8s-app: cerebro-dev
    version: v0.8.1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cerebro-dev
  namespace: elasticsearch
  labels:
    k8s-app: cerebro-dev
    version: v0.8.1
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cerebro-dev
      version: v0.8.1
  template:
    metadata:
      labels:
        k8s-app: cerebro-dev
        version: v0.8.1
    spec:
      containers:
      - name: cerebro-dev
        image: yannart/cerebro:0.8.1
        resources:
          limits:
            cpu: 8000m
            memory: 16Gi
          requests:
            cpu: 8000m
            memory: 16Gi
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        ports:
        - containerPort: 9000
          name: ui
          protocol: TCP
        volumeMounts:
        - name: cerebro-config
          mountPath: /opt/cerebro/conf/application.conf
          subPath: application.conf
      volumes:
      - name: cerebro-config
        configMap:
            name: cerebro-cfg
