kind: Namespace
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    env: elasticsearch-dev
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-dev
  namespace: elasticsearch
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: elasticsearch
  name: elasticsearch-dev
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2
subjects:
- kind: ServiceAccount
  name: elasticsearch-dev
  namespace: elasticsearch
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "rbac.authorization.k8s.io"

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-dev
  namespace: elasticsearch
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2
spec:
  selector:
    k8s-app: elasticsearch-dev
    version: v6.3.2
  clusterIP: None
  ports:
    - name: rest
      port: 9200
    - name: inter-node
      port: 9300

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-dev
  namespace: elasticsearch
  labels:
    k8s-app: elasticsearch-dev
    version: v6.3.2
spec:
  serviceName: elasticsearch-dev
  replicas: 3
  selector:
    matchLabels:
      k8s-app: elasticsearch-dev
      version: v6.3.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-dev
        version: v6.3.2
    spec:
      containers:
      - name: elasticsearch-dev
        image: lincappu/es-6.3.2-crack:test
        resources:
            limits:
              memory: "20Gi"
            requests:
              memory: "1Gi"
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-dev
          mountPath: /usr/share/elasticsearch/data
        - name: snapshot-data
          mountPath: /snapshot
        env:
          - name: cluster.name
            value: elasticsearch-dev
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch-dev-0.elasticsearch-dev,elasticsearch-dev-1.elasticsearch-dev,elasticsearch-dev-2.elasticsearch-dev"
          - name: discovery.zen.minimum_master_nodes
            value: "2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      volumes:
      - name: snapshot-data
        hostPath:
          path: /snapshot
          type: Directory
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-dev
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      - name: increase-ml-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -l unlimited"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-dev
      labels:
        k8s-app: elasticsearch-dev
        version: v6.3.2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 10Gi
