apiVersion: v1
kind: Service
metadata:
  name: job-case-parse-svc
  labels:
    app: job-case-parse
spec:
  selector:
    app: job-case-parse
  clusterIP: None
  sessionAffinity: ClientIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-case-parse
  labels:
    app: job-case-parse
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: job-case-parse
  template:
    metadata:
      labels:
        app: job-case-parse
    spec:
      containers:
      - name: job-case-parse
        image: 172.16.82.12:32022/case-parse-job:mq-201911072037
#        resources:
#          limits:
#            cpu: "8000m"
#            memory: "8Gi"
#          requests:
#            cpu: "1000m"
#            memory: "1Gi"
