kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-node3-pvc-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: alicloud-nas
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka-node3-pvc-log
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: alicloud-nas
