apiVersion: v1
kind: Service
metadata:
  name: ai-ner-svc
  labels:
    app: ai-ner-dev
spec:
  selector:
    app: ai-ner-dev
  clusterIP: None
  sessionAffinity: ClientIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ner
  labels:
    app: ai-ner-dev
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  selector:
    matchLabels:
      app: ai-ner-dev
  template:
    metadata:
      labels:
        app: ai-ner-dev
    spec:
      containers:
      - name: ai-ner-dev
        image: 172.16.82.12:32022/ai-ner-dev:dev
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "8000m"
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
