apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-node3
    version: v2.11
  name: kafka-node3
  namespace: devops
spec:
  clusterIP: None
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    name: kafka
  - port: 9099
    protocol: TCP
    targetPort: 9099
    name: jmx
  selector:
    app: kafka-node3
    version: v2.11
  sessionAffinity: None
  type: ClusterIP
