apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-node2
    version: v2.11
  name: kafka-node2-extenal-http
  namespace: devops
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30920
    name: kafka
  - port: 9099
    protocol: TCP
    targetPort: 9099
    name: jmx
  selector:
    app: kafka-node2
    version: v2.11
  sessionAffinity: None
  type: NodePort
