apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk-node1
  name: zk-node1-extenal
  namespace: devops
spec:
  type: NodePort
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 30810
    name: client
  selector:
    app: zk-node1
