apiVersion: v1
kind: Service
metadata:
  labels:
    app: zk-node3
  name: zk-node3-extenal
  namespace: devops
spec:
  type: NodePort
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 30830
    name: client
  selector:
    app: zk-node3
